### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by zhyvr** [Safflower/solve-me#3]
Why I get this error  is there anyhow I can fix that 
It's in index.php 

Thanks

**Comment by Safflower** [comment]
I was changing the server settings for a while.
Thank you

**Comment by zhyvr** [comment]
Can you fix it ? :D

**Comment by Safflower** [comment]
umm.. 
this source code is no problem on my server.
but if you have a 404 error, maybe <code>.htaccess</code> file wasn't working on your server.
Is your server apache?

**Comment by zhyvr** [comment]
I'm using 000webhost so I think

**Comment by zhyvr** [comment]
can you send me your .htaccess file code

**Comment by Safflower** [comment]
ok, i uploaded it.

**Comment by zhyvr** [comment]
thanks it helps 
================================
but when i want to join shows this 
https://i.imgur.com/n9fjQYa.jpg

and should i write (MD5) here
https://i.imgur.com/Kh8n9U2.jpg

**Comment by Safflower** [comment]
that error show when occur unexpected situation.
did you install the <code>init.sql</code> file?

**Comment by zhyvr** [comment]
yes

**Comment by zhyvr** [comment]
# plz can you fix it :1st_place_medal:
